//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://flights.com")]
[System.Xml.Serialization.XmlRootAttribute("user", Namespace = "http://flights.com", IsNullable = false)]
public partial class entity
{

    private ulong idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hotel.com")]
[System.Xml.Serialization.XmlRootAttribute("user", Namespace = "http://hotel.com", IsNullable = false)]
public partial class Menu : Entity
{

    private string nameField;

    private string ingridientsField;

    private double priceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string ingridients
    {
        get
        {
            return this.ingridientsField;
        }
        set
        {
            this.ingridientsField = value;
        }
    }

    /// <remarks/>
    public double price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Menu))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hotel.com")]
public partial class Entity
{

    private ulong idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hotel.com")]
[System.Xml.Serialization.XmlRootAttribute("room", Namespace = "http://hotel.com", IsNullable = false)]
public partial class Room : Entity
{

    private ulong roomIdField;

    private byte numberField;

    private string categoriField;

    private byte countField;

    private double priceField;

    /// <remarks/>
    public ulong roomId
    {
        get
        {
            return this.roomIdField;
        }
        set
        {
            this.roomIdField = value;
        }
    }

    /// <remarks/>
    public byte number
    {
        get
        {
            return this.numberField;
        }
        set
        {
            this.numberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string categori
    {
        get
        {
            return this.categoriField;
        }
        set
        {
            this.categoriField = value;
        }
    }

    /// <remarks/>
    public byte count
    {
        get
        {
            return this.countField;
        }
        set
        {
            this.countField = value;
        }
    }

    /// <remarks/>
    public double price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hotel.com")]
[System.Xml.Serialization.XmlRootAttribute("spa", Namespace = "http://hotel.com", IsNullable = false)]
public partial class Spa : Entity
{

    private string nameField;

    private double priceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public double price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hotel.com")]
[System.Xml.Serialization.XmlRootAttribute("order", Namespace = "http://hotel.com", IsNullable = false)]
public partial class Order : Entity
{

    private ulong orderIdField;

    public OrderStatus orderStatusField;

    private ulong userField;

    private ulong roomid;

    private ulong spaid;

    private ulong menuid;

    private Room[]roomField;

    private Spa[] spaField;

    private Menu[] menuField;
    public List<Order> _ordersField;


    /// <remarks/>
    public ulong userId
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }

    /// <remarks/>
    public ulong roomId
    {
        get
        {
            return this.roomid;
        }
        set
        {
            this.roomid = value;
        }
    }

    /// <remarks/>
    public ulong spaId
    {
        get
        {
            return this.spaid;
        }
        set
        {
            this.spaid = value;
        }
    }
    /// <remarks/>
    public ulong menuId
    {
        get
        {
            return this.menuid;
        }
        set
        {
            this.menuid = value;
        }
    }
    /// <remarks/>
    public ulong orderId
    {
        get
        {
            return this.orderIdField;
        }
        set
        {
            this.orderIdField = value;
        }
    }

    /// <remarks/>
    public OrderStatus orderStatus
    {
        get
        {
            return this.orderStatusField;
        }
        set
        {
            this.orderStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("room")]
    public Room[] room
    {
        get
        {
            return this.roomField;
        }
        set
        {
            this.roomField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("menu")]
    public Menu[] menu
    {
        get
        {
            return this.menuField;
        }
        set
        {
            this.menuField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("spa")]
    public Spa[] spa
    {
        get
        {
            return this.spaField;
        }
        set
        {
            this.spaField = value;
        }
    }
    [System.Xml.Serialization.XmlElementAttribute("order")]
    public List<Order> orders
    {
        get
        {
            return this._ordersField ??= new List<Order>();
        }
        set
        {
            this._ordersField = value;
        }
    }

    public override string ToString()
    {
        var info = "\nOrder Entity";
        info = info + $"\nOrderID: {id}, OrderStatus: {orderStatus}, UserID: {userId}, RoomID: {roomId}, SpaID: {spaId}, MenuID: {menuId}";
        return info;
    }










    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hotel.com")]
    public enum OrderStatus
    {

        /// <remarks/>
        New,

        /// <remarks/>
        Active,

        /// <remarks/>
        Finished,
    }


}




/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hotel.com")]
[System.Xml.Serialization.XmlRootAttribute("user", Namespace = "http://hotel.com", IsNullable = false)]
public partial class User : Entity
{

    private string nameField;

    private string surnameField;

    private string middleNameField;

    private string phoneField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string surname
    {
        get
        {
            return this.surnameField;
        }
        set
        {
            this.surnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string middleName
    {
        get
        {
            return this.middleNameField;
        }
        set
        {
            this.middleNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
}


